version: '3.8'

services:
  web:
    build: .
    container_name: ai-assistant
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=False
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    env_file:
      - .env
    volumes:
      - ./src:/app/src:ro
      - ./.secret_key:/app/.secret_key:ro
    networks:
      - ai-network
    restart: unless-stopped
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - ai-network
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama-data:

networks:
  ai-network:
    driver: bridge