version: '3.8'

services:
  web:
    build: .
    container_name: ai-assistant-dev
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=True
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./config.py:/app/config.py
      - ./run.py:/app/run.py
      - ./.secret_key:/app/.secret_key:ro
    networks:
      - ai-network
    restart: unless-stopped

networks:
  ai-network:
    driver: bridge