version: '3.8'

# This compose file uses local wheels for completely offline builds
# First run: ./download-wheels.sh to populate the wheels directory

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.offline  # Uses only local wheels
    image: ai-assistant:offline
    container_name: ai-assistant-offline
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=False
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - DATABASE_PATH=/app/data/work_assistant.db
      - CHROMA_PERSIST_DIRECTORY=/app/data/chroma_db
      - ANONYMIZED_TELEMETRY=False
    env_file:
      - .env
    volumes:
      # Mount data directory for persistent storage
      - ./data:/app/data
      # Mount secret key directory
      - ./.secret_key:/app/.secret_key
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"