#!/bin/bash
echo "=== Context Window Configuration ==="
echo ""
echo "Current model: phi3:mini"
echo "Maximum supported: 128K tokens"
echo ""
echo "Recommended settings:"
echo "  1. 8K   - Fast, minimal VRAM (default before)"
echo "  2. 32K  - Balanced (current setting)"
echo "  3. 64K  - Large conversations"
echo "  4. 128K - Maximum context (may be slow)"
echo ""
echo "To change, set NUM_CTX environment variable:"
echo "  export NUM_CTX=32768"
echo ""
echo "Or edit config.py directly."
echo ""
echo "Note: Larger context = more VRAM usage & slower processing"